### ISSUE TITLE
Can only recognize one cd drive with cd_drives()

### ISSUE THREAD

**Issue by miasinterestinglife** [matix64/eject-rs#1]
Currently the program only finds a single disk drive when using cd_drives() to discover all of them. This should be easily fixable by replace the hard-coded "/dev/sr0" with a function to find all drives named "/dev/sr*", or by adding a few more hard-coded drive numbers. I know this isn't a regular thing to have more than one but it can happen and is quite annoying if i can't use this tool anymore.
Something like this:
`pub const CDROM_PATHS: &[&str] = &["/dev/cdrom", "/dev/sr0", "/dev/sr1", "/dev/sr2", "/dev/sr3"];`

**Comment by matix64** [comment]
The `CDROM_PATHS` constant is only used in the `first_cdrom` function. `cd_drives` uses the iterator implemented a few lines below in that same file which should find all files of the form `/dev/srX` if they are consecutive.
```rust
fn next(&mut self) -> Option<Self::Item> {
    let path = PathBuf::from(format!("/dev/sr{}", self.next_i));
    if path.exists() {
        self.next_i += 1;
        Some(path)
    } else {
        None
    }
}
```
Sadly I don't have any CD drives to test this with, but I have confirmed it works if I manually create the files. Can you tell me the paths of the drives in your PC? I'm pretty sure the problem is they are not what I expected.

**Comment by miasinterestinglife** [comment]
So I know this is very uncommon but I use two CD drives and due to some
bugs in my os sometimes only one of them gets recognized so /dev/sr0
doesn't exist but /dev/sr1 does, sometimes I even get /dev/sr2 when it
feels like it. So the issue is that the next CD drive always returns None
of there is no /dev/sr0 (is it possible to just get the lowest number of
drive?) I'd be happy to test that for you

**Comment by matix64** [comment]
Ok I think it's fixed, I just made it check all symlinks in `/dev/disk/by-id`, or all files in `/dev` if that doesn't work, and find everything that starts with `/dev/sr` followed by a number. There's probably a more efficient way to do it but I guess this is ok for the moment.

The fix is on a new branch: [`list_cd_drives_fix`](https://github.com/matix64/eject-rs/tree/list_cd_drives_fix)
You can test it either by cloning it and running `cargo test d_cd_drives_list -- --show-output --ignored` or including it in your project with
```toml
eject = { git = "https://github.com/matix64/eject-rs.git", branch = "list_cd_drives_fix" }
```
Note that `cd_drives()` now returns a Result in case that reading `/dev/disk/by-id` and `/dev` both fail. Which is very unlikely afaik.

**Comment by miasinterestinglife** [comment]
Works like a charm! Thank you very much and have a very nice day :)
